//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int Id { get; set; }
        public System.DateTime ReturnedDate { get; set; }
        public Nullable<System.DateTime> RealReturnedDate { get; set; }
        public System.DateTime TakenDate { get; set; }
        public string Status { get; set; }
    
        public virtual Book book { get; set; }
        public virtual Reader reader { get; set; }
    }
}
